apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj-a-deployment
  labels:
    app: projA
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projA
  template:
    metadata:
      labels:
        app: projA
    spec:
      containers:
        - image: 10.1.2.58:30002/test-project1/projecta:v1
          name: projecta
          ports:
            - containerPort: 8080
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: proj-a
spec:
  selector:
    app: projA
  ports:
  - port: 80
    targetPort: 8080

